### ISSUE TITLE
Could not find package chiragit007/Customgrid at any version for your minimum-stability (beta)

### ISSUE THREAD

**Issue by comunidademagento** [chiragit007/Customgrid#1]
I try installa composer require chiragit007/Customgrid

![captura de tela de 2015-09-15 11 51 26](https://cloud.githubusercontent.com/assets/7476455/9879986/24bdce4e-5ba0-11e5-814e-02ce1c47aea8.png)

**Comment by comunidademagento** [comment]
See image.

I got it enabale module ./bin/magento module:enable Chirag_Mygrid

![captura de tela de 2015-09-15 18 39 49](https://cloud.githubusercontent.com/assets/7476455/9891036/d13559ec-5bd9-11e5-81bc-46b67251a4df.png)

**Comment by comunidademagento** [comment]
Hello Chirag,

You have a blog?

Please post tutorial explaining how to develop this module.

How to load the form on the front end to publish questions?

Thanks!!!

**Comment by chiragit007** [comment]
Hi -

As of now I don't do blog posts that much but I can definitely show the steps on how to do it here.

Regards,
Chirag Bhavsar

**Comment by chiragit007** [comment]
Hi -

Should I close this as issue ? I will write the explanation under the description section of the Git.

**Comment by comunidademagento** [comment]
Hello Chirag,

Yes, close this issue.

Send me link with the explanation under the description section of the Git.

Thanks!!!
